### PR TITLE
Update to React 18

### PR DESCRIPTION
**Pull request by jhserodio**
## React 18
[issue 120](https://github.com/lxieyang/chrome-extension-boilerplate-react/issues/120)

- update to react 18
- remove unnecessary hot reload replacements
- update code examples for render
- update docs for react new version

### CODE REVIEW

**Review by hari-bhandari — APPROVED** [review]
upgraded to react 18

**Review by GXFG — APPROVED** [review]

**Comment by sbahir** [comment]
@jhserodio I tested your changes and it seems like I cannot set anymore breakpoints to debug the unbundled reactJS file from VScode.

It works perfectly on the latest stable version.
Do you have this same issue? 
If so, do you know what could have broken it? 

It's quite painful to try to debug the bundled reactjs files with your changes

**Comment by sbahir** [comment]
@jhserodio @lxieyang 

You need to make a change in `webpack.config.js` to fix webpack source mapping

```js
if (env.NODE_ENV === 'development') {
  // options.devtool = 'cheap-module-source-map';
  options.devtool = 'inline-cheap-module-source-map';
}
```

Otherwise, we can't link react source files in DevTools `sources` 

Please let me know if you have any questions or feedback

**Comment by veeramarni** [comment]
@sbahir  any fix for breakpoint issue?

**Comment by lxieyang** [comment]
Done!

**Pull request closed without merging**
